### ISSUE TITLE
[v14] quality_control_oca trigger or workflow improvement such as inspection is triggered before action validate (before validate picking)

### ISSUE THREAD

**Issue by bunhin** [OCA/manufacture#1044]
In many use cases, the inspection is needed or wanted before the stock move. Such as when we purchase an item, We only want to receive the purchased item ( Can Validate Reciept Picking when the inspection is done and passed the quality criteria).
With the current state, the inspection is triggered after we validate the picking.

How do we implement the inspection step before validating the picking in other word, validating the picking is only allowed when inspection is success and done (confirmed)

**Comment by diggy128** [comment]
Hi @bunhin.
Unfortunately the quality control modules haven't seen many improvements since v8.
This issue is one of the difficulties the current trigger approach presents. As is, the quality control modules do not enforce any control on any other model. 
On the other hand in your case it probably would not make sense to block the validation of the receiving picking and the reasons are simple and ones we have also come across:
1) Say you have an incoming delivery that fails quality control and you  want to return the products to the supplier. In order to do so you have to validate the picking and issue a return note back to the supplier.
2) Say you have an incoming delivery of two (or more) different products or even one product with different lot/serial and only one of them fails quality control. In this case you should validate the picking and release all products / lots that pass the QC and block the one failing so as to return them to the supplier (or even scrap them) and in any case block from using them (whether that means selling them, using them in a production, consuming them, etc).

These are only two of the cases the existing modules do not handle. As is, the pass / fail of a QC test is only informative and does not allow to block any further action.

**Comment by bunhin** [comment]
Hi @diggy128,

Thank you for your kind reply. I understand and agree with the point. Because the quality_control module does not yet have that kind of granularity (can pass one lot or reject the other lot for example) seems hard to be used as a control mechanism for a receiving for example.

Maybe someday when the improvement on the module is made, can consider a "pre-move" check as well as an addition to the existing "post-move" check trigger.   Some use cases will need post-move ( such as when the check is advanced and need a reasonably long duration), but some other cases may need a pre-move check.

Thanks,
