### ISSUE TITLE
[8.0][quality_control_mrp] Link between Manufacturing order and quality control inspection lost

### ISSUE THREAD

**Issue by mamaf** [OCA/manufacture#107]
From the Manufacturing order I created a quality control inspection by clicking on the button Inspections
In the inspection form, I set the link to the correct MO and save, but when I come back to the MO, the butonn is still displaying 0 inspections and when I click on the button, the list of inspections is empty

**Comment by pedrobaeza** [comment]
That's because inspections are only linked to production orders when auto-created from the manufacture trigger. You can't link by hand an inspection to a production order, although you fill the reference field with a MO.

**Comment by mamaf** [comment]
And how do you specify the "manufacture trigger" ??

**Comment by pedrobaeza** [comment]
You have them on the product form.

**Comment by anajuaristi** [comment]
About this, just today I received a suggestion from a customer who told me about the link/shorcut from Mo and Wo to inspection exists we could allow to create as many manual inpections needed in any step of the production filling automatically Mo/product inspection fields. Otherwise there is no way to have informed those fields.
On the other side, they also sugested to have editable all link fields on manual inspection so you would not need to use the field reference.
What do you think about both suggestions? Indeed, I find them quite logical

**Comment by pedrobaeza** [comment]
Yes, it can be an improvement. In fact, it's simple to be put, and I have made it in https://github.com/OCA/manufacture/commit/e50f8c556f89411e3ab8afd0ebb5bf3c4d29d5ab

**Comment by mamaf** [comment]
Yes that is also the need of one of my prospects
There is also a need to have a simple screen (same type as warehouse barecode scanning) used during operations to simply start / pause / end work orders and enter simple test results during inspections
If I win this opportunity, I will keep you in touch with the requirements
