### ISSUE TITLE
[10.0] [mrp_mto_with_stock] Not Working as Desired

### ISSUE THREAD

**Issue by gokhanerdogdu** [OCA/manufacture#234]
Hello Community,

mrp_mto_with_stock module is not working as desired for the below scenario. I want to check whether it is a bug or I am missing something.

We have product A and product A consists of product B and C, 1 unit in each for the BOM. We have 5 units for each them in stock and we have a sales order of 20 units of product A. 

All the settings are made as described for the module.

1- Manufacture Order is created automatically, but with a problem that 5 units in stock is not taken into account for the auto created MO. Since we have 5 units of Product A in stock, we expect the MO created for 15 units of product A, but it was created for 20 units of product A neglecting the 5 units in stock.
2- Product B and C in stocks are well realized and automatic purchase orders are created correctly. 15 units of Product B and C. No problem on this.
3- When the manufacturing order is completed, the number of used products are doubled as 40 units for each of Product B and Product C. This is another problem.

Thanks and regards.

**Comment by LoisRForgeFlow** [comment]
Hi @gokhanerdogdu 

The functionality of this module refers to the components in a manufacturing order, you got a "unexpected" 20-units MO for product A but if you look at the components to feed this MO you will see that 5 are fetched from stock and the remaining 15 generated a procurement. This, is exactly what this module is intended for.

Your issue is more in the procurement of the parent product (product A) which is created from your SO and then generates the MO to fulfill the need. In this case maybe the module [stock_mts_mto_rule](https://github.com/OCA/stock-logistics-warehouse/tree/10.0/stock_mts_mto_rule) could help you. (@florian-dacosta could you confirm it?)

**Comment by florian-dacosta** [comment]
I don't think stock_mts_mto_rule can help in this case.
Actually, I don't really get the problem. From what I understand, there is no product A in stock, but there are 5 product B and 5 product C, correct?
In this case, it is working as expected, a manufacture order is created with 20 product A.
Purchase order for product B and C are for 15 product only as there are already 5 stock.
So all good no?
stock_mts_mto_rule will help in case you have 5 products A in stock. Then the manufacture order should be created for only 15 products A.
