### ISSUE TITLE
[11.0] mrp_production_split_manual

### ISSUE THREAD

**Issue by max3903** [OCA/manufacture#275]
# Module description

This module allows the production manager to split a manufacturing order based on the minimum capacity of the work centers involved in the routing.

# Configuration

* Set the capacity on your work centers

# Usage

* Create a manufacturing order for a product using the work center configured previously
* Set a quantity to produce greater than 1
* Click on "Split"
* The wizard will show the "Total Quantity to Produce", the "Maximum Capacity" and lines where you can decided how you want to split the quantity. The first line is the existing MO.

**Comment by LoisRForgeFlow** [comment]
have a look at [mrp_production_request](https://github.com/OCA/manufacture/tree/10.0/mrp_production_request). It is on v10, but with some little tweak or extension it could cover your need.

**Comment by LoisRForgeFlow** [comment]
Just trying to save you some time, for the record you can check how I got to manufacturing requests, the [inicial approach](https://github.com/OCA/manufacture/pull/208) was trying something similar to what you are describing here, but I abandoned it in favor of manufacturing requests.

**Comment by jgrandguillaume** [comment]
Hi @lreficent 

We got to this point because we need to produce several serialized products at the same time and this is currently not supported by Odoo v11 (neither older version though).

You cannot produce more than one product at a time on a given workcenter if this product is serialized...

Splitting the MO is one of the option, but not yet convinced of the approach... But I wanted to let you know.

Regards,

Joël
