### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by rogie69** [OCA/manufacture#306]
Hi,

We have tested the module and can seem to get it to work as expected both on our server and runbot. We have set up a product LE2000, perhaps you could have a look and tell us where we are going wrong.

Many thanks

**Comment by pedrobaeza** [comment]
Which module? Which version? Which steps to reproduce? If you want to receive help, you should provide enough information. Take into account that this is voluntary, so following http://www.catb.org/esr/faqs/smart-questions.html helps you to get an answer

**Comment by rogie69** [comment]
Hi,
Apologies to not being clear.
the module is MRP MTO with Stock running on Odoo v11 (we have tried it on both our v.11 enterprise test server and also on runbot (from the link on the app page) when we did not get the expected result.

Scenario
We have set up a product LE2000 (on runbot), with ICE CREAM as its BOMs, checked Manufacture route and assigned a MTO/MTS Locations (on runbot as My Co/Stock). We put 2 in stock and then put on a sales order for 3 units and confirmed it.


Expected Behaviour
Generate MO for remaining 1 unit.


Actual Behaviour
Reserves 2 Unit on Delivery Order (Standard behaviour) and does not raise any MO for the remaining 1 unit.

We recreated this scenario on runbot, can you please have a look on it as we might have missed something there.

Thanks

**Comment by pedrobaeza** [comment]
@lreficent any clue?

**Comment by LoisRForgeFlow** [comment]
Hi @rogie69,

The module does not work directly from a SO, it works from nested MOs (i.e. MOs created from other MOs). Example (using a demo product that you can find in runbot already configurated):

![image](https://user-images.githubusercontent.com/23449160/45549834-63a92700-b829-11e8-9958-9ab991a94e21.png)

0. You add 5 units on WH/stock for subproduct 1.
1. You create a SO for 2 units of TOP.
2. 3 MOs have been auto-created: 
* MO1: 2 units of TOP.
* MO2: 5 units of subproduct 1 (instead of 10, we already have 5 in stock).
* MO3: 4 units of subproduct 2 (full quantity needed as we had 0 stock).

![image](https://user-images.githubusercontent.com/23449160/45550039-0cf01d00-b82a-11e8-9295-9fd2857d0111.png)

Hope this is clearer now. I'm seeing many issue regarding this module, I would be helpful if you create a Pull Request enhancing the description and usage in the README of the module.
