### ISSUE TITLE
[RFC][12.0][mrp_mts_with_stock] Create lite version of mrp_mts_with_stock

### ISSUE THREAD

**Issue by kos94ok-3D** [OCA/manufacture#451]
As I see this module has many opened issues, so maybe need to refactor module.
My Idea base on manufacturing steps introduced in Odoo 12.
1. add a constraint for a warehouse that disallow use MTS+MTO with manufacture_steps == 'mrp_one_steps'
2. add new mto+mts rule with a lower sequence in "My Company: Pick components and then manufacture" route
As a result, not need to install mrp_mto_with_stock_purchase and resolve existing bugs.
What do you think about it?
@sergiocorato, @rousseldenis, @florian-dacosta, @bodedra, @LoisRForgeFlow , @JordiBForgeFlow, @MiquelRForgeFlow
Please give me any feedback. I need to know it is a good or bad idea.

**Comment by kos94ok-3D** [comment]
#411

**Comment by sergiocorato** [comment]
@kos94ok-3D Can you make a PR for this?

**Comment by kos94ok-3D** [comment]
I think better create a new module with the name mrp_mts_with_stock_lite.
ping @sergiocorato, @OCA/manufacturing-maintainers

**Comment by sergiocorato** [comment]
:+1:

**Comment by LoisRForgeFlow** [comment]
I don't understand why do create a new module instead of fixing what you claim has bugs.

**Comment by kos94ok-3D** [comment]
HI, @LoisRForgeFlow.
1. I don`t know how to migrate mrp_mts_with_stock 11 to a new workflow because it can not work with manufacturing in one step
2. I didn`t get feedback on what is better to migrate or create new

**Comment by LoisRForgeFlow** [comment]
what you mean is that https://github.com/OCA/manufacture/pull/411 is not working and you don't know how to fix it?

What I can say is the following:
* I would prefer if we get merged the migration to v12 in the above PR and then open a new one with your improvements.
* I am not using the module anymore as It was an oversimplification, so it won't be expending much time trying to fix it.

So, if you really don't find a better way to achieve your goal than creating a new module I guess I cannot block you because I don't have the time to help in fixing that.

**Comment by kos94ok-3D** [comment]
`what you mean is that #411 is not working and you don't know how to fix it?`
It is a problem which you tried to fix in  mrp_mto_with_stock, but I decided to add a constraint because I can work without manufacturing in one step.
Ok, I wait while PR #411 will be merged
