### ISSUE TITLE
mrp_sale_info Issue

### ISSUE THREAD

**Issue by murande** [OCA/manufacture#760]
module: mrp_sale_info
version: 13.0

**Steps to reproduce**
- ...
![Screenshot from 2022-02-21 16-35-18](https://user-images.githubusercontent.com/43172894/154976053-1627fd99-9ece-4d41-90ff-16ca8de9fd9c.png)

**Comment by aduijs** [comment]
this is also the case in version 14.0
i think it has to do with the fact you need to add the reordering rule of the product.
it looks like the "reordering rule" is creating the work order, instead of the Sales Order (so no sales order specific info like SO, Cust etc is passed with it)

**Comment by aduijs** [comment]
i was able to "fix" it with the help of Lucas on the odoo forum. (so actually it isnt broken)
the reason why it stays empty is because the MOs are generated by the replenish (reordering rules) and not from the SO directly.
here is the link to the forum.
https://www.odoo.com/nl_NL/forum/help-1/odoo14-15ce-sales-to-mrp-difference-in-comparison-with-older-versions-200683

here is a copy of the text:
If you use the MTO route it will write the SO to the reference field on the MO.
Enable it here: Inventory > Configuration > Routes > (Filter for 'Archived') then unarchive it
On the product template, tick MTO + Manufacture as the possible routes
Remove any Reordering rules on the product as they might interfere with the MTO route.
If you have done the above, then when a sales order with an MTO product is confirmed, it will create a MO.

The Sales Order will have a smart button to link to the MO, the MO will have a smart button to link to the sales order, and the reference field on the MO will be the Sales Order that created it.

**Comment by quentinDupont** [comment]
For search engine : 

Issue related to sale order field that is empty on production order.

Since v13, route `Replenish on Order (MTO)` is archived by default. You need to unarchive this and select this route on your Product.

Thanks for this issue and answer !
