### ISSUE TITLE
fixed batch size for work orders

### ISSUE THREAD

**Issue by samuelosram** [OCA/manufacture#859]
Our workorders have all fixed number of item. e.g. our punch produces exactly 50 pieces. So when a order/rule needs 60 pieces (eg) we have to produce 100 (or even 150 ... 200 ... 250 ... )

Makes a mrp-module sence that is constraint to a fixed batch size (eg. the number of items of the bom) or a multiple number of this?

Or is a other workflow more useful?

**Comment by diggy128** [comment]
You could achieve what you want by putting the production multiple (on your case 50) in a stock reordering rule for that part.

When the procurement cron action runs the stock rule will generate a production order to meet your demand at the closest multiple that meets the demand.

Eg you have 5 parts at hand and a production order requires 20.
When the cron runs it will create a production order for that part with a quantity multiple of that set in the stock reordering rule so that the demand is fulfilled aka 50 parts.
When completing the production orders you will have 35 parts at hand.

**Comment by samuelosram** [comment]
Yes thats possible. but i think the wrong position. this works only when the workorder initiated with reorder rule.

**Comment by diggy128** [comment]
That's true, so I assume you create your manufacturing order as parts are needed, correct?

Even if so, taming the power of stock reordering rules will help you further down the road as you implement and use odoo more.

You could set a rule and create an automated action that once a production order is created, it corrects the qty to be produced by the rule multiple. If you at some point choose to implement JIT manufacturing you just disable the action, enable the rule and set the built to order route on the part.

Just my 2cents.

**Comment by samuelosram** [comment]
thx @diggy128

I think about exclusivly use of reorder rules is a good idea regarding workflow of odoo.
